### ISSUE TITLE
Staring Contest with Wither Skeletons Crashes Client

### ISSUE THREAD

**Issue by SteamCrunk** [rwtema/modjam2018#8] opened 2018-04-24 01:23 UTC
Potential interaction with a mod like FoamFix or BetterFPS, but I figured I'd report it here as that is what the log is throwing.

`[18:58:24] [Server thread/WARN]: Failed to handle packet for /66.190.180.140:53881
net.minecraft.util.ReportedException: Ticking player
	at net.minecraft.entity.player.EntityPlayerMP.func_71127_g(EntityPlayerMP.java:459) ~[oq.class:?]
	at net.minecraft.network.NetHandlerPlayServer.func_73660_a(NetHandlerPlayServer.java:173) ~[pa.class:?]
	at net.minecraftforge.fml.common.network.handshake.NetworkDispatcher$1.func_73660_a(NetworkDispatcher.java:209) ~[NetworkDispatcher$1.class:?]
	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:285) ~[gw.class:?]
	at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:180) [oz.class:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:788) [MinecraftServer.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:396) [nz.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:666) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:524) [MinecraftServer.class:?]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_144]
Caused by: java.lang.NoSuchMethodError: net.minecraft.util.math.AxisAlignedBB.<init>(Lnet/minecraft/util/math/Vec3d;Lnet/minecraft/util/math/Vec3d;)V
	at com.rwtema.monkmod.advancements.criteria.MonkRequirementStare.getStareEntity(MonkRequirementStare.java:36) ~[MonkRequirementStare.class:?]
	at com.rwtema.monkmod.advancements.criteria.MonkRequirementStare.doTick(MonkRequirementStare.java:79) ~[MonkRequirementStare.class:?]
	at com.rwtema.monkmod.advancements.criteria.MonkRequirementTick.walk(MonkRequirementTick.java:25) ~[MonkRequirementTick.class:?]
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_1207_MonkRequirementTick_walk_PlayerTickEvent.invoke(.dynamic) ~[?:?]
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90) ~[ASMEventHandler.class:?]
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:179) ~[EventBus.class:?]
	at net.minecraftforge.fml.common.FMLCommonHandler.onPlayerPostTick(FMLCommonHandler.java:369) ~[FMLCommonHandler.class:?]
	at net.minecraft.entity.player.EntityPlayer.func_184808_cD(EntityPlayer.java:378) ~[aed.class:?]
	at net.minecraft.entity.player.EntityPlayer.func_70071_h_(EntityPlayer.java:288) ~[aed.class:?]
	at net.minecraft.entity.player.EntityPlayerMP.func_71127_g(EntityPlayerMP.java:382) ~[oq.class:?]
	... 9 more`

**Modlist:**
Immersive Engineering
Botania
Thermal Expansion
Thermal Foundation
Applied Energistics 2
Thermal Dynamics
Draconic Evolution
Forestry
Gendustry
Mystical Agriculture
Mekanism
Industrial Foregoing
Thermal Cultivation
Immersive Petroleum
Project E
Avaritia
Journey Map
Storage Drawers
Iron Chests
Extra Utilities 2
Chisel
Actually Additions
Better Builders Wands
Chisels & Bits
RFTools
Ender Storage
Redstone Arsenal
Open Blocks Elevator
RFTools Control
Chest Transporter
RFTools Dimensions
Quark
Psi
XNet
Not Enough Wands
Simply Jetpacks 2
Magic Bees
Mekanism Generators
Mekanism Tools
Portal Gun
Solar Flux Reborn
The Erebus
Long Fall Boots
Fairy Lights
Open Glider
Useful Nullifiers
Woot
/dank/null
Nature's Compass
More Bees
Career Bees
Scannable
Rainbow Oak Trees
Tinkers Construct
PamsClaySpawn
Trumpet Skeleton
CraftTweaker
ModTweaker
Inventory Tweaks
Mouse Tweaks
JEI
Baubles
FTBUtilities
AppleSkin
Just Enough Resources
UniDict
The One Probe
BetterFPS
KleeSlabs
Quick Leaf Decay
Nether Portal Fix
JEI Bees
AkashicTome
Morph-O-Tool
Better Questing
Diet Hoppers
Swing Through Grass
Vein Miner
Fence Jumper
Integration Foregoing
Help Fixer
Lapis Stays In The Enchanting Table
Faster Ladder Climbing
Stacksize
Better Than Mending
Bow Infinity Fix
Infinity and Mending Unnerf
Neat
Mod Name Tooltip
Client Tweaks
Clarity
NoFOV
IKWID
Keyboard Wizard
Controlling
Clean View
Better Placement
More Overlays
autoreglib
codechickenlib
p455w0rdslib
brandons core
valkyrie lib
ftbl
bdlib
teslacore lib
mtlib
cucumber
mcjtylib
ichunutil
CoFHcore
hammer core
redstone flux
chameleon
CoFHworld
mantle
wanionlib
placebo
Shadowfacts Forgelin
Connected Textures Mod
Reliquary
Roots 2
Embers
Magical Psi
Soot
Bonfires
Guide-API
FoamFix
AE2-Stuff
Creeper Confetti
Fast Workbench
Torcherino
Lore Expansion
Silents Gems
SilentLib
XTones
Cosmetic Armor Reworked
Realistic Item Drops
Immersive Railroading
Laser Level
SonarCore
TOP Addons
FluxNetworks
Exchangers
The Lost Cities
Translocators
Thut Core
Baubley Heart Containers
Furnace Overhaul
Avaritia Tweaks
Iskallium Reactors
InGameAccountSwitcher
TrackAPI
Lunatrius Core
Forge Multi Part CBE
Ender Core
EnderIO
Tiny Progressions
Cyclic
The Monk Mod
Librarian Lib
Totem Expansion
Electro Blobs Wizardry
Find Me
Portality
Equivalent Energistics
Thermal Innovation
Shoulder Surfing Reloaded
Wizardry
Vise
Iron Backpacks
Better Questing Standard

**Comment by SteamCrunk** [comment] 2018-04-24 23:11
Did some more testing, it seems to be a Multiplayer only issue (assuming the mod list posted above).  Not able to replicate in single player at the current time, will do some drill down testing.

**Comment by SteamCrunk** [comment] 2018-04-25 00:52
In doing more testing, haven't figured out if it is a mod interaction issue yet, but the problem doesn't appear until level 14.  

Tested on a multiplayer server, the monk player keeps getting disconnected due to server error when they first see a wither skeleton, persists regardless of location past that point.  Reducing the monk level to 13 or lower via /monk setlevel resolves issue until they reach level 14 again.

**Comment by rwtema** [comment] 2018-04-29 09:43
Dupe of #1

**Closed by rwtema** 2018-04-29 09:43 UTC
